### ISSUE TITLE
Not on packagist?

### ISSUE THREAD

**Issue by chrisnharvey** [adam-paterson/oauth2-stripe#1]
Hi there,

Great package!

I couldn't seem to find this package on packagist, so I had to add the repo manually in my composer.json file.

Do you have any plans to put this package on packagist?

**Comment by adam-paterson** [comment]
Thanks @chrisnharvey, I thought I had added it to Packagist. I'll have a look now and make sure it is!

Thanks for using the package!

**Comment by adam-paterson** [comment]
Looks like there was a spelling mistake in my vendor name, I've amended this and re-submitted the package to packagist. Let me know if that fixes your issue

**Comment by chrisnharvey** [comment]
All working perfectly now.

Thanks for this and keep up the good work!

**Comment by adam-paterson** [comment]
@chrisnharvey no problem, good luck with your application.
