### ISSUE TITLE
Publishable Key Not Accessible

### ISSUE THREAD

**Issue by shadle10** [adam-paterson/oauth2-stripe#3]
Hi Adam - I'm loving this but the Stripe Publishable Key isn't passed along to your classes.  In order to get the Stripe Publishable Key, I had to edit the getAccessToken method within the OAuth2 library's AbstractProvider class. I returned the prepared variable instead of the token variable.  This is obviously a poor solution and not ideal.  I wondered if you had an alternative way to get the publishable key. Thanks!

`````` php
public function getAccessToken($grant, array $options = [])
    {
        $grant = $this->verifyGrant($grant);

        $params = [
            'client_id'     => $this->clientId,
            'client_secret' => $this->clientSecret,
            'redirect_uri'  => $this->redirectUri,
        ];

        $params   = $grant->prepareRequestParameters($params, $options);
        $request  = $this->getAccessTokenRequest($params);
        $response = $this->getResponse($request);
        $prepared = $this->prepareAccessTokenResponse($response);
        return $prepared;

        /*$token    = $this->createAccessToken($prepared, $grant);
                  return $token;*/
    }```
``````

**Comment by adam-paterson** [comment]
This should resolve the issue you're having. Contexted provided in https://github.com/thephpleague/oauth2-client/issues/377

@shadle10 Thanks for using the package!

**Comment by adam-paterson** [comment]
@shadle10 fixed in release [1.1.1](https://github.com/adam-paterson/oauth2-stripe/releases/tag/1.1.1)

**Comment by shadle10** [comment]
Thanks for the quick response and the great support @adam-paterson!

**Comment by adam-paterson** [comment]
@shadle10 no problem, good luck in your application
