### ISSUE TITLE
Update client dependency

### ISSUE THREAD

**Issue by jasonvarga** [adam-paterson/oauth2-stripe#7]
Can this package be updated to depend on the 2.* version of `league/oauth2-client`?

I hate opening an issue without a PR but I'm not sure what's involved. I've forked this repo and simply updated the composer dependency - everything seemed to work great. I don't know if there's anything else to be done.

**Comment by adam-paterson** [comment]
I've been keeping an eye out on the base repo and I don't think updating would introduce breaking changes. Feel free to submit a PR and I'll test it thoroughly tomorrow.

**Comment by jasonvarga** [comment]
Cool, thanks! Opened #8 for you.
